### ISSUE TITLE
Podling lists should use $project.incubator.apache.org

### ISSUE THREAD

**Issue by stain** [apache/incubator-ponymail#100]
e.g. for the podling Juneau, the email address should be `dev@juneau.incubator.apache.org` - not `dev@juneau.apache.org`

https://lists.apache.org/list.html?dev@juneau.apache.org  should present itself as `dev@juneau.incubator.apache.org` - as emailing `dev@juneau.apache.org` even fails with a DNS error.  This also mean that it's Subscribe button is wrong, as it links to `mailto:dev-subscribe@juneau.apache.org`.

**Comment by Humbedooh** [comment]
Please don't conflate Pony Mail with lists.apache.org - the project is not in charge of the installation.

**Comment by stain** [comment]
Thanks, @Humbedooh - raised as https://issues.apache.org/jira/browse/INFRA-12192 instead.

I guess #92 is not appropriate here either then?
