### ISSUE TITLE
Unable to view list

### ISSUE THREAD

**Issue by justinmclean** [apache/incubator-ponymail#104]
I'm an ASF member and when logged in I can't see any anything in trademarks@hadoop.

Here's the URL:
https://lists.apache.org/list.html?trademarks@hadoop.apache.org

It displays:
"No emails found fitting this criteria"

AFAIK their should be some content there.

**Comment by Humbedooh** [comment]
Please direct that question to the Apache Infrastructure team, the Pony Mail project can't really help with specific installations.
