### ISSUE TITLE
Bug: links in stats pane don't set up the correct date range

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#106]
Ponymail displays a stats pane showing the number of mails for the Top 10 contributors in the blob.

If the user is logged in, then the contributors are turned into links.

I would expect each link to show the emails for the contributor that are part of the blob, however that does not work properly because the search date range is not always updated correctly.

For example, start with:

https://lists.apache.org/list.html?dev@ponymail.apache.org:2016-6

Click on Daniel Gruno (12 emails)

The output shows mail threads including Daniel Gruno (as expected)

Now click on 2016 July

Click on Daniel Gruno (16 mails)

The display reverts to June 2016, with only 12 emails

**Comment by Humbedooh** [comment]
Iiiinteresting! It would appear a variable has gotten stuck somewhere.
I'll take a look when time allows :)
