### ISSUE TITLE
Bug: mbox download silently ignores private emails

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#108]
The mbox download function silently omits private mails.

This does not make sense: the mails are visible and the raw contents can readily be displayed, so it should be possible to download them as part of the mbox download.

**Comment by Humbedooh** [comment]
This is currently by design, and thus not a bug. If you want the behavior to change, I would suggest a discussion on the mailing list :)

**Comment by sebbASF** [comment]
Exclusion is one issue. Silently ignoring mails is another.

I would say it is a bug that the user is not warned that some/all mails which are visible on screen are excluded from the download.
