### ISSUE TITLE
Bug: emails with no body content are ignored

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#109]
As the subject says: emails which have no body content are ignored.

Such e-mails are perfectly valid and are regularly used for the output from cron jobs etc.

**Comment by Humbedooh** [comment]
If you could point to a place in the code where it ignores 0-length bodies, that would be helpful. As far as I can tell, it only ignores if the body cannot be found, not simply if it's empty.

**Comment by sebbASF** [comment]
For several examples of missing e-mails, see site-dev in early August.

Several of the mails with the subject "WARN: Apache Kudu (kudu) missing from /data/committees.xml" are missing from lists.apache.org.

Sample missing mail:

http://mail-archives.apache.org/mod_mbox/www-site-dev/201608.mbox/raw/%3C20160801010004.284E160326%40projects-vm.apache.org%3E

The mail has no body, but as far as I am aware it's still valid. 

In particular, the mail is stored by the ASF mail archive, and should be stored by ponymail/lists.a.o.

**Comment by sebbASF** [comment]
AFAICT the main problem is that the archiver#compute_updates() method checks if the body is True ("if body or attachments:") however an empty body is not True. This affects the importer.

In the case of the archiver, an empty message causes an Exception:

>>>>>>
cat x | /usr/local/bin/python3.4 ponymail/tools/archiver.py --verbose
Traceback (most recent call last):
  File "ponymail/tools/archiver.py", line 613, in <module>
    lid, mid = foo.archive_message(msg_metadata, msg)
  File "tools/archiver.py", line 389, in archive_message
    id=ojson['mid'],
TypeError: 'NoneType' object is not subscriptable
Archiving failed!: 'NoneType' object is not subscriptable
Could not parse email: Archiving to ES failed
<<<<<<
