### ISSUE TITLE
Invalid command 'LuaScope'

### ISSUE THREAD

**Issue by djKooks** [apache/incubator-ponymail#155]
On setup Ponymail on my laptop(Mac OS X 10.10), I have some issue.
```
AH00526: Syntax error on line 102 of /private/etc/apache2/extra/httpd-vhosts.conf:
Invalid command 'LuaScope', perhaps misspelled or defined by a module not included in the server configuration
```
I refer the settings on configs/ponymail_httpd.conf file for setup vhost.
Is there something need to setup more on Mac? Because I only find setups for Linux on guide.

Thanks.

**Comment by Humbedooh** [comment]
Yes, mod_lua needs to be loaded for this to work. See http://modlua.org/gs/installing - the module should be there already (unless you built from source), as it's a standard core module, so you should only need to add the LoadModule directive to your configuration.

**Comment by djKooks** [comment]
@Humbedooh Sorry to bother, but I'm keep stuck while installing. I setup Lua and vhost setup, but still have issue like this when I run `sudo apachectl -k restart`.

```
httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load libexec/apache2/mod_lua.so into server: dlopen(/usr/libexec/apache2/mod_lua.so, 10): Symbol not found: _luaL_addlstring\n  Referenced from: /usr/libexec/apache2/mod_lua.so\n  Expected in: flat namespace\n in /usr/libexec/apache2/mod_lua.so
```

Do you know something about this?
Thanks.

**Comment by sebbASF** [comment]
I suspect this is due to trying to use Lua 5.3.
Apache mod_lua only supports 5.2.x; see #148

**Comment by djKooks** [comment]
@sebbASF Thanks for help! It worked~
