### ISSUE TITLE
Bug: pcall() idiom to protect against elastic.lua exceptions is flawed

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#162]
The elastic.lua wrapper module can throw an error for some valid invocations - e.g. document not found.

The way this is handled currently is as follows:

local _, doc = pcall(function() return elastic.get("mbox", eid or "hmm") end)
if not doc or not doc.subject then ... end

However, if elastic.get() throws an error, the doc variable will be the error message string.
AFAICT it's not possible for doc to be false/nil currently, so it's not useful as a check.

**Comment by Humbedooh** [comment]
I think the main issue here is, elastic shouldn't error out on a 404, only other 4xx/5xx errors.
it should be changed to uhm... something like "if code != 200 and code != 404" in there...

**Comment by sebbASF** [comment]
Agreed, elastic should only throw an error for real errors; that would simplify the code as the pcall() wrapper would not be needed at all.

AFAICT the code only works because errors return a string so references such as doc.subject will be false.

**Comment by sebbASF** [comment]
It looks as though 404s are only to be expected from elastic.get.
So it might make sense to only add a check for 404 when the caller is get.

**Comment by sebbASF** [comment]
Further checks show that some code does not check if the returned doc is valid after calling elastic.get()

A better solution would be to add an optional get parameter; if specified then it will return for 404. Then only code that is expecting a 404 will ever see one.

The alternative is to always use pcall, but that catches all errors.
It would be better to let these get reported, rather than assuming there has been a 404.
