### ISSUE TITLE
Add mbox download to private lists

### ISSUE THREAD

**Issue by ShaneCurcuru** [apache/incubator-ponymail#169]
The download feature is incredibly useful, but is also needed on private lists.  What are the privacy/security/technical issues preventing this from appearing on private lists?  

Presumably the download for private? would also be a configuration setting for the server install, so the admin can decide.

Separately, it would be nice to make the download feature more obvious/have help for the end user.  (something I'll write eventually once I get into the code).

**Comment by sebbASF** [comment]
At present the code fetches all the ids [1] for the messages in the date range.
It then throws away [2] all the private ids.
However it could first check if the user has access to the list, as is done in other modules.

[1] the ids are needed to access the actual message source
[2] a bit wasteful, see #153

**Comment by Humbedooh** [comment]
It was a design choice when it was made. I'm open to changing this to allow private lists to be downloaded.

**Comment by sebbASF** [comment]
If it was a design choice, why does the implementation fetch private e-mail ids?

**Comment by Humbedooh** [comment]
well, it allows for faster changing into fetching private emails? :)
All we would need to do is check against the AAA and allow it through if so.
