### ISSUE TITLE
Make it clearer when you're not logged in.

### ISSUE THREAD

**Issue by johnament** [apache/incubator-ponymail#195]
First time users struggle with Ponymail, its not clear when they're logged in or not.  Ponymail uses a generic person icon, and make it multicolor when they are logged in.

I would recommend:
- Don't show the person icon if the user is not logged in.
- Show a textual link "Login" instead
- If clicking on a mail link that they cannot access, if a user is not logged in show the login link in the body (does not mean they will have access to the email, but its a clear indication of their login state)

**Comment by sebbASF** [comment]
Emails that are inaccessible to the current session (whether logged in or not) should be treated as non-existent, so there should be no links to them.

**Comment by gstein** [comment]
Right, @sebbASF ... it should not leak the email's existence.

That said, the page that mentions the email does not exist or you have no access ... places a "login" link within the prose. It is *easily* missed (I have one empirical case of providing such support to somebody, plus my own experience) ... I would suggest moving that link to a clear and obvious button.

**Comment by gstein** [comment]
Oh: and to @johnament's point: using color as the *only* determinate factor is a basic interface no-no. Some people have problems with detecting color(s). So I concur with John's point, but also from an HI standpoint: switching from grey to colored is not a good UI design.

**Comment by johnament** [comment]
Err why was this closed?

**Comment by sebbASF** [comment]
Because the problem has been addressed? The page now shows "Login" as suggested.
