### ISSUE TITLE
Confusing parameter name (--rename) in copy-list.py

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#207]
The copy-list.py tool uses the following syntax:

copy-list.py --source listname [--rename listname] [--newdb dbname]

It would make more sense for the --rename parameter to be called --newlist or --target

**Comment by cpoerschke** [comment]
#376 proposes to have the rename (no pun intended) from `--rename` to `--target` in both `copy-list.py` and `edit-list.py`

**Comment by Humbedooh** [comment]
I think it makes sense in copy-list, but...seems confusing in edit-list. I'm torn here..

**Comment by sebbASF** [comment]
The original issue was about copy-list only.
Let's not confuse the issue by involving other scripts; use another issue for that if required.
