### ISSUE TITLE
Website Fix - security issue reporting

### ISSUE THREAD

**Issue by johnament** [apache/incubator-ponymail#242]
http://ponymail.incubator.apache.org/support.html#securityissues

Security issues should be reported to the PPMC, IPMC and security.

**Comment by sebbASF** [comment]
I'm not sure the IPMC need to be informed?

**Comment by sebbASF** [comment]
If the IPMC is to be informed, obviously it should be to private@ rather than general@

**Comment by sebbASF** [comment]
The normal procedure is to inform security@apache; they will then inform the (P)PMC.
