### ISSUE TITLE
Bug: attempt to get length of field 'body' (a userdata value)

### ISSUE THREAD

**Issue by ilgrosso** [apache/incubator-ponymail#254]
I am running the master branch into a private server.
After pulling the latest changes, I have started receiving the following error:

```
/var/www/ponymail/api/stats.lua:694: attempt to get length of field 'body' (a userdata value)
```

on some of the lists. No mail is displayed.

Any hint or workaround? Thanks!

**Comment by Humbedooh** [comment]
yup, I know that one - it's when you have a null body. the fix is to check for JSON.nil right before. I can push a fix to master at some point.

**Comment by Humbedooh** [comment]
essentially, you would add this right before line 694:
email.body = (email.body ~= JSON.null) and email.body or ""

**Comment by ilgrosso** [comment]
Yup, thanks @Humbedooh it works!

Any reason for not considering it as a proper fix? If so I could just push it.

**Comment by Humbedooh** [comment]
feel free to fix it :) I just haven't had the time (ApacheCon etc)

**Comment by ilgrosso** [comment]
If you don't mind, I'll go on with that - don't understand LUA at all but it smells as a god fix ;-)

**Comment by sebbASF** [comment]
There are other places where the body field can be dereferenced.
It's possible to fix it in elastic.lua (I have a patch that works for me if it's of interest).

**Comment by ilgrosso** [comment]
Sure, why not? I am not familiar with LUA but is there any way to "centralize" such null safety check? Does it make sense?

**Comment by sebbASF** [comment]
Since the body can only be obtained by calling elastic.lua methods, in theory it is possible to centralise it.

The scan/scroll method was a bit tricky, but I got it working for me.

I don't have time just now, but hopefully later today.
