### ISSUE TITLE
Enh: preferences.lua should search for 'not public' rather than private

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#270]
preferences.lua currently drops mailing lists that have had a least one private mail in the last 20 years. This excludes many lists that are mixed private and public.

Rather than searching for lists with any private mails, it might be better to search for lists without any public mails. However this would potentially show the statistics relating to private mails.

**Comment by Humbedooh** [comment]
searching for private emails is, however, vastly faster than looking for lists without public email - I'm not sure if the proposed approach is feasible.

**Comment by sebbASF** [comment]
There is another possible approach:
Get the names of lists:
- containing at least one private mail
- containing at least one public mail
And get the counts of emails for the last 90 days for the same categories.

The output can then be generated by merging in data from the private lists to which the user has access.

The aggregations for the private mails don't even need to be done unless the user is logged in.
[The caches would need to be adjusted accordingly]

See also #272 and #70

**Comment by sebbASF** [comment]
It looks like the following query returns all the data needed in a single pass.

The data is aggregated by list name, within that by public/private and within that by age.

The response should be sufficient to construct the output data.

GET /ponymail/mbox/_search
{
  "size": 0,
  "aggs": {
    "lists": {
      "terms": {
        "field": "list_raw"
      },
      "aggs": {
        "privacy": {
          "terms": {
            "field": "private"
          },
          "aggs": {
            "recent": {
              "range": {
                "field": "epoch",
                "ranges": [
                  {"from": <now-90d>}
                ]
              }
            }
          }
        }
      }
    }
  }
}

**Comment by sebbASF** [comment]
One can also change the order so that the privacy buckets contain the lists buckets.
This might make it simpler to process the response for the case where the user is not logged in

**Comment by sebbASF** [comment]
This has been fixed by using aggregates
