### ISSUE TITLE
How to unsubscribe from a list

### ISSUE THREAD

**Issue by juangamnik** [apache/incubator-ponymail#360]
I am subscribed for years in `j-users@xalan.apache.org` and cannot find any way to unsubscribe from this list. Most mailing lists add a unsubscribe link in the footer or at least allow to unsubscribe on the page. The site offers me to login in via apache oauth or google, but I don't think that I have a real account there, because my subscription is older than 6 years (and another mailing list software has been used back then). Is there an option to unsubscribe from pony mail and if yes, how can I do it and perhaps can you make this option more prominent?

**Comment by sebbASF** [comment]
Ponymail is an archive service for mailing lists. It is not a list provider.

Different mailing lists have different ways of managing subscriptions.
You need to contact the mailing list. In most cases the list headers will show how to unsubscribe.
If you use the View Source button on any of the j-users mails, you should see a line like:

List-Unsubscribe: <mailto:j-users-unsubscribe@xalan.apache.org>

**Comment by juangamnik** [comment]
Great, thanks. Perhaps there should be a link to the list provider on the list archive page.
