### ISSUE TITLE
Bug: message source displayed as base64 encoded data

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#371]
The source for the following mail:

https://lists.apache.org/thread.html/277d98905e53608d9fdc95a6dea94001a03c6a8d4f4aa08cb76db5de@%3Cdev.ofbiz.apache.org%3E

i.e.

https://lists.apache.org/api/source.lua/277d98905e53608d9fdc95a6dea94001a03c6a8d4f4aa08cb76db5de@%3Cdev.ofbiz.apache.org%3E

Is displayed as

a blob of base64 encoded data.

**Comment by sebbASF** [comment]
There are several other such in the May 2017 mbox.

**Comment by sebbASF** [comment]
Other samples
https://lists.apache.org/api/source.lua/426f2f7b791bbe1dd0aead8ca90ea52f04bfd1a20e523609118578d2@%3Cdev.ofbiz.apache.org%3E
https://lists.apache.org/api/source.lua/8fd70019d6ffc76901eb8a3e5bdd377a31f45b5c13ac1413420ab68e@%3Cdev.ofbiz.apache.org%3E
https://lists.apache.org/api/source.lua/bb35b02eb9a42b882d012cc055f50e9380b55b0354f0b5a5c5c81ca8@%3Cdev.ofbiz.apache.org%3E
https://lists.apache.org/api/source.lua/14a320da362be560ce90dc8bceef441242c3c0ca133252bb2ffdd5a2@%3Cdev.ofbiz.apache.org%3E

All of them were sent by Jacques Le Roux; however not all of his mails are affected, for example:

https://lists.apache.org/api/source.lua/cba468a40c6e9971a9ddc9a524f628cb07f693cf3186312a85d00f6d@%3Cdev.ofbiz.apache.org%3E
and
https://lists.apache.org/api/source.lua/a5290434baacdcb2ffe07eb73b9db379be05b56f9ba2c272a710d14a@%3Cdev.ofbiz.apache.org%3E

**Comment by sebbASF** [comment]
It looks as though something changed around 02 May 2017 06:38:53.
There are two copies of the same message from Jacques Le Roux:
https://lists.apache.org/thread.html/cba468a40c6e9971a9ddc9a524f628cb07f693cf3186312a85d00f6d@%3Cdev.ofbiz.apache.org%3E
https://lists.apache.org/thread.html/a43b24548b6e2278c31c1a03d157b8e9c6479ffa3579c10d66564942@%3Cdev.ofbiz.apache.org%3E

The first has a readable source doc; the second is base64

**Comment by Humbedooh** [comment]
From what I can gather, this was due to an upgrade in the archiver script on the box(es). This may be a regression in the archiver.

**Comment by sebbASF** [comment]
Note: It does look as though all the base64 encoded messages were sent by Jacques Le Roux, starting at 02 May 2017 06:38:53.

**Comment by Humbedooh** [comment]
Here's a simple workaround for the base64 encoding when it happens:
~~~
--- a/site/api/source.lua
+++ b/site/api/source.lua
@@ -46,6 +46,10 @@ function handle(r)
         if aaa.canAccessDoc(r, doc, account) then
             local doc_raw = elastic.get('mbox_source', doc.request_id)
             if doc_raw then
+                -- If this could be base64, try to convert it.
+                if (#doc_raw.source % 4 == 0) then -- base64 is always multiples of 4, this is the fastest test.
+                    pcall(function() doc_raw.source = r:base64_decode(doc_raw.source) end) -- try to convert, fall back to original if failed
+                end
                 r:puts(doc_raw.source)
             else
                 r:puts("Could not find the email source, sorry!")
~~~

**Comment by sebbASF** [comment]
However why does it happen in the first place?

**Comment by Humbedooh** [comment]
Because of https://github.com/apache/incubator-ponymail/commit/117db841331bb93d71763fe361d4455d71e716b0 which converts into base64 on some occasions.

This patch is more complete:
~~~
--- a/site/api/source.lua
+++ b/site/api/source.lua
@@ -23,6 +23,15 @@ local user = require 'lib/user'
 local cross = require 'lib/cross'
 local utils = require 'lib/utils'
 
+function is_base64(msg)
+   if #msg % 4 == 0 then
+      if not msg:match("([^a-zA-Z0-9+=/])") then
+         return true
+      end
+   end
+   return false
+end
+
 function handle(r)
     -- content is currently utf-8, see #367
     cross.contentType(r, "text/plain; charset=utf-8")
@@ -46,6 +55,10 @@ function handle(r)
         if aaa.canAccessDoc(r, doc, account) then
             local doc_raw = elastic.get('mbox_source', doc.request_id)
             if doc_raw then
+                -- If this could be base64, try to convert it.
+                if is_base64(doc_raw.source) then
+                    pcall(function() doc_raw.source = r:base64_decode(doc_raw.source) end)
+                end
                 r:puts(doc_raw.source)
             else
                 r:puts("Could not find the email source, sorry!")
~~~

**Comment by sebbASF** [comment]
However 117db84 already allows for base64 encoding in elastic.lua.

Either the check there is not  always detecting b64, or lists.a.o has not got the correct code installed.

**Comment by Humbedooh** [comment]
lists.a.o is not running master as master is not compatible with 0.9 plugins. I suspect just the archiver was updated. I'll ping them about incorporating the base64 changes

**Comment by sebbASF** [comment]
There may be other changes that are required to run with the master version of the archiver.
It's not possible in general to pick and choose which updates to use. Even the GUI may depend on backend changes or vice-versa.

**Comment by sebbASF** [comment]
It looks as though most of the sources are now displayed OK.

However the following has a corrupted source:

https://lists.apache.org/thread.html/a5290434baacdcb2ffe07eb73b9db379be05b56f9ba2c272a710d14a@%3Cdev.ofbiz.apache.org%3E

Also the mbox download does not decode the base64 entries.

**Comment by Humbedooh** [comment]
Nothing Pony Mail can do about that, I'd punt it to ASF Infra.

**Comment by sebbASF** [comment]
Not sure what 'that' means here?

**Comment by Humbedooh** [comment]
'that' means the previous comment.

**Comment by sebbASF** [comment]
The corrupted source has been fixed.

However the mbox download is now truncated; the last few lines read:

<h3>Error!</h3>
<pre>/var/www/ponymail_asf/site/api/lib/elastic.lua:72: attempt to index global 'r' (a nil value)</pre>

Looks like more partial code updates have been applied to lists.a.o

**Comment by sebbASF** [comment]
The download issue now seems to have been fixed.
