### ISSUE TITLE
Import generates "raw" e-mails

### ISSUE THREAD

**Issue by ilgrosso** [apache/incubator-ponymail#379]
After recent commits, when running import from mbox, I can see few "phantom" e-mails, with:

* sender: none
* subject: `(no subject)`
* body: whole e-mail content (in mbox format)

**Comment by sebbASF** [comment]
Need some sample input to debug this, or pointer to an existing mbox file that causes the issue.

**Comment by ilgrosso** [comment]
Such e-mails are unfortunately private, I cannot share it.

FWIW, when I checkout the repo to the commit before 211ddde32bffea1511df6a70fd172ffa33131c79, everything works as expected.

**Comment by sebbASF** [comment]
The commit 767d8f8 is the last commit currently and only affects the display of the email body, and should only apply to mails with no body entries, so I don't see how that can have the effect you describe.

What View Mode and theme did you use?

Were all mails affected, or just some of the recent ones?
Did the problem only apply to recent imports, or were existing mails affected as well?

**Comment by ilgrosso** [comment]
Indeed, after deleting the list and re-importing, everything is back at work, with latest HEAD.
Sorry for the noise.
