### ISSUE TITLE
Binary attachment 'mangled'

### ISSUE THREAD

**Issue by ilgrosso** [apache/incubator-ponymail#384]
I am experiencing this problem with my company deployment, but it is now happening to the [Apache Syncope user@ mailing list](https://lists.apache.org/thread.html/8bd5e23e4f43e386303b4ddca8a8f42effd79503ed7c5d725aa811f5@%3Cuser.syncope.apache.org%3E).

As you can see, there is an attachment, `error-logs.zip`, which cannot be opened if downloaded from there:
```
$ unzip -l Downloads/error-logs.zip 
Archive:  Downloads/error-logs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Downloads/error-logs.zip or
        Downloads/error-logs.zip.zip, and cannot find Downloads/error-logs.zip.ZIP, period.
```

When you download it from [Markmail](http://markmail.org/message/w272msajghgctvtn) instead, it works like a charm (please also note the difference in size).

**Comment by ilgrosso** [comment]
Thanks @Humbedooh !

**Comment by ilgrosso** [comment]
Shall the ML on lists.apache.org be re-indexed then?

**Comment by Humbedooh** [comment]
no, downloading from that is also fixed with this change. the sources are okay.

**Comment by ilgrosso** [comment]
I see: I was wondering if that was correct because of the displayed size (different than in Markmail), but everything seems to work fine. Thanks again!
