### ISSUE TITLE
Website Fix: Incubator Project Link points to Apache Johnzon

### ISSUE THREAD

**Issue by pmkuny** [apache/incubator-ponymail#386]
The link at https://incubator.apache.org/projects/ponymail.html under "Pony Mail Project Incubation Status" links to johnzon.apache.org instead of ponymail.apache.org

Not sure if this belongs in the incubator-specific issues.

**Comment by sebbASF** [comment]
[It's the podling that sets up and maintains the file so this is the correct place to report the problem.]

The source file has been editted. Not sure how long it takes for the update to be displayed.

**Comment by sebbASF** [comment]
Thanks for the report; now fixed
