### ISSUE TITLE
Enh: 'cluster' generator ids are not sufficiently unique

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#398]
The redundant ID generator is documented as not guaranteeing unique ids.

It currently includes (if present):
Body
List Id
Date
Sender
Subject
Attachment hashes

Whilst these are unlikely to generate duplicates, it's not impossible: for example the same (undated) message could be sent multiple times to the same list.

I'm not sure why Message-ID is not included in the list of fields, as it's designed for such usage.

It should be included in the hash (if present).

Note: since the redundant generator is new since 0.9, it has yet to be included in a release.
So it's possible to change the algorithm without causing problems.

If there are any other  invariant fields that warrant inclusion this should also be done now.

**Comment by Humbedooh** [comment]
message-id could certainly be used instead of or in conjunction with the Date field.
Another thing I'm pondering on is making the redundant generator whitespace-ignorant - that is, crop any trailing whitespace from the end of the message to counter LF->CRLF conversions etc by simply ignoring ANY whitespace at the end of a message.

**Comment by sebbASF** [comment]
The result of trimming trailing white-space would be to only keep one of the inputs.
How do you know which is correct?
Far better to eliminate the cause of any differences upstream where the original input is available.

**Comment by Humbedooh** [comment]
by trimming all trailing whitespace, they would both be identical, and thus both correct.

**Comment by sebbASF** [comment]
Huh? Valid source messages can end in trailing whitespace.

If the different archivers are presented with inputs that only differ in the amount of trailing whitespace, at most one of the inputs properly represents the original message.
If these inputs all generate the same id then the last one to be posted wins.
There is no guarantee that this is the correct representation.

**Comment by sebbASF** [comment]
The 'redundant' generator has been renamed to 'cluster'

**Comment by sebbASF** [comment]
Regarding whitespace trimming that should be the subject of a separate issue.

**Comment by sebbASF** [comment]
FTR: Message-Id is now included in the cluster algorithm; however unfortunately the value is not canonicalised first.
