### ISSUE TITLE
UI: Manage Email Addresses process is not clear

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#40]
Clicking Associate on the Manage Email Addresses page responds with:

"Your association request has been handled. Please check your inbox! Depending on grey-listing etc, it may take up to 15 minutes before your confirmation email arrives."

This implies that there is nothing further to do. However that is not the case as the email states:

"You (or someone else) has requested to merge this email address with the account ... in Pony Mail
If you wish to complete this merge, please visit https://..."

It's also not clear what 'merge this email address' means.
It's confusing for the mail to use 'merge' when the page uses 'associate'

**Comment by sebbASF** [comment]
Here is a patch to use associate rather than merge in the e-mail:
[merge.patch.txt](https://github.com/quenda/ponymail/files/277185/merge.patch.txt)

**Comment by Humbedooh** [comment]
could you submit this in the form of a pull request instead?
