### ISSUE TITLE
mbox.lua output filename does not match ISO standard

### ISSUE THREAD

**Issue by ShaneCurcuru** [apache/incubator-ponymail#420]
Using the great api/mbox.lua to export MBOX files is great, except the filenames use a plain digit for the month, not an ISO 8601 format.  This means exporting multiple MBOX files doesn't sort in time order in the output, as users would expect.

Presumably the fix would be to ensure the MBOX filename always uses two digits for the month:
https://github.com/apache/incubator-ponymail/blob/master/site/api/mbox.lua#L69

**Comment by ShaneCurcuru** [comment]
Hmmm. They might sort normally, but having a fixed width filename on export that matches the input timespans= API would still be useful.

**Comment by sebbASF** [comment]
Huh? they don't sort correctly on my system:

$ ls -1 dev_po*.mbox
dev_ponymail_apache_org_2017-1.mbox
dev_ponymail_apache_org_2017-11.mbox
dev_ponymail_apache_org_2017-12.mbox
dev_ponymail_apache_org_2017-2.mbox

I agree the month should be padded with a leading 0 if required.
This could be done in the GUI, but I think it's better done in the backend.
