### ISSUE TITLE
Dump documents to disk on ES failure

### ISSUE THREAD

**Issue by Humbedooh** [apache/incubator-ponymail#423]
Currently, when PM fails to archive to ES for whatever reason (typically because the DB is unavailable), it just breaks and emails are in risk of ending up nowhere.

I propose we add a --dumponfail directive that spits out a JSON object to a directory with the various documents that _need_ to be stored. A process can then later scoop up those json files and push them to ES when the DB is back in working condition.

**Comment by sebbASF** [comment]
Code causes archiver to ignore failures if dumponfail is not defined

**Comment by sebbASF** [comment]
Created new bug #449
