### ISSUE TITLE
Indentation in mail content (leading white-space) not shown

### ISSUE THREAD

**Issue by ddekany** [apache/incubator-ponymail#432]
Currently you are using `white-space: pre-line` on the `pre` that holds the mail body (for text/plain mail content). This un-indents the lines of the mail, hence making source code quotations (and bullet listings) hard to read. Using `white-space: pre-wrap` fixes that. (Note sure why `white-space: pre-line` was chosen originally though... but as it collapses sequences of whitespace, including `[lineBreak, indentation]`, it can't be right for text/plain.)

**Comment by sebbASF** [comment]
Can you please provide some sample links to show the problem?

**Comment by ddekany** [comment]
Sure: [https://lists.apache.org/thread.html/0bc90b453f106adfdb6ba1fc91cbbb63daa386be3fe7e2463362a2bd@<dev.freemarker.apache.org>](https://lists.apache.org/thread.html/0bc90b453f106adfdb6ba1fc91cbbb63daa386be3fe7e2463362a2bd@<dev.freemarker.apache.org>)

(A different issue, but this also happens to be a case where the reply mails aren't shown for some reason... If you click the same mail on https://lists.apache.org/list.html?dev@freemarker.apache.org (i.e., not through a permalink), they are shown.)

**Comment by sebbASF** [comment]
Thanks for the sample.
Please file a separate issue for a separate bug.
