### ISSUE TITLE
Emails not showing after importing from archive

### ISSUE THREAD

**Issue by dimidd** [apache/incubator-ponymail#433]
Hello,

I might be missing something trivial, but after installing ponymail, and importing emails from an mbox file, I don't see any lists in pony's homepage. This is the command I've used to import:
`python3 /var/www/ponymail/tools/import-mbox.py --lid 'mylist' --timeout 12000 --source mylist_all.mbox`

**Comment by sebbASF** [comment]
Were there any messages reported when you did the import?

**Comment by dimidd** [comment]
Unfortunately, I didn't save the log, but it said all messages were imported successfully but a few.

**Comment by Humbedooh** [comment]
When you say 'emails not showing', do you mean the list names are not showing on the index page, or do you have the lists but no specific emails in the list view? If the former, what happens if you manually go to list.html?$foo@$bar (where $foo@$bar is your list name) ?

**Comment by dimidd** [comment]
Thanks, the former. `list.html?mylist` is also empty.
screenshot: ![](https://i.imgur.com/4BL6vU2.png)

**Comment by sebbASF** [comment]
I think the problem might be the list-id.

If you used
 --lid 'mylist' 
as per the description it looks like this won't be displayed.

Try

 --lid 'mylist@mydom.tld' 

instead and see what happens.

AFAICT there need to be at least 3 parts to the list-id, separated by '@' and '.'

**Comment by sebbASF** [comment]
The following path should show what mailing lists are available:

http://your.host/api/preferences.lua

**Comment by dimidd** [comment]
`/api/preferences.lua` showed that `lists` is empty. Anyhow, I re-imported, this time using `--lid mylist@example.com`, and everything works now. Thank you sir.
