### ISSUE TITLE
Bug: broken Permalink - points to wrong mailing list

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#46]
https://github.com/quenda/ponymail/issues/41 was closed, but the issue was not fixed

**Comment by Humbedooh** [comment]
it's _not_ a bug, it's a configuration issue. If you have a specific issue with that service, I suggest you reach out to the people in charge of it.

**Comment by sebbASF** [comment]
A similar message was sent to two different mailing lists separately.
How is it not a bug that the same short hash is generated for these two *different* messages?

Seems to me that the hash does not include sufficient context.

**Comment by Humbedooh** [comment]
See aa98961019c7c660c8c610449f5640afa1228cfb - this should be considered a done deal now.

**Comment by sebbASF** [comment]
The message on the derby dev list has the permalink:

https://lists.apache.org/thread.html/Z7qd2pd84pll5sl

This still points to the wrong message.

**Comment by Humbedooh** [comment]
That's hardly our fault :) If you want a specific instance to be re-indexed, contact the appropriate people in charge of that.

**Comment by sebbASF** [comment]
Huh? Surely the incorrect (duplicate) hash was caused by a bug?

**Comment by Humbedooh** [comment]
But we don't run lists.apache.org :) We're a software community, not a service provider.
