### ISSUE TITLE
Bug: thread.lua fetches replies from other lists

### ISSUE THREAD

**Issue by dimidd** [apache/incubator-ponymail#466]
How to reproduce: import the same mbox file to two different lists.
Open a thread of list1, replies which belong to list2 will be shown as well.
I guess we could amend this line (43) in `api/thread.lua`:
`local docs = elastic.findFast( ('in-reply-to:"%s" OR references:"%s"'):format(emid, emid), 50, "mbox")` to account for the list-id as well.

**Comment by sebbASF** [comment]
If the same mbox file is present on multiple lists, then it's not surprising that PonyMail shows the mails from both.
Applying the suggested fix will probably break threads that reply to multiple lists.
If a reply is sent to a different list, it's still the same thread...

I don't think this is a bug.

**Comment by dimidd** [comment]
I see, thanks.
