### ISSUE TITLE
Bug: cannot download more than 10K mails to a mbox file

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#475]
The code has a limit of 10K mails when fetching mails to write to an mbox file.
Whilst it may be necessary to limit the number of mails fetched in a single request, it seems wrong to limit the number of mails that can be written to the output mailbox

**Comment by sebbASF** [comment]
Unfortunately scroll sort does not work as expected, at least on ES 2.4.0.
Needs more research.

**Comment by sebbASF** [comment]
Even if the mails were correctly sorted by epoch, the order in the mbox file might not correspond with the order they arrived (duplicate epochs; original date may not be correct), and may not agree with the order in which the messages were posted to the list (variable delays in transit).

However, it would be useful if the order were at least similar to that which occurs for smaller mboxes when scrolling does not need to be used.

**Comment by Humbedooh** [comment]
I don't think we should be aiming at supporting all the way to 2.4.0 at all.
5.x and above should be plenty, people can upgrade their clusters if need be.

**Comment by sebbASF** [comment]
Doh!
Just noticed that the elastic.lua scroll function forces the sort to use _doc.
The problem is with elastic.lua#scroll, not ES
