### ISSUE TITLE
Errors with Elasticsearch 5.x

### ISSUE THREAD

**Issue by ilgrosso** [apache/incubator-ponymail#489]
I initially tried with ES 6.x, but I wasn't able to update index creation correctly, so I reverted to ES 5.x, with which everything seems to work except for the following.

When running

```
python3 edit-list.py --delete --source "idal2.tirasa.net"
```

I receive the following error: 
```
Beginning list edit:
  - List ID: <idal2.tirasa.net>
  - Action: Delete emails (sources will be kept!)
Updating docs...
Traceback (most recent call last):
  File "edit-list.py", line 180, in <module>
    terms
  File "/var/www/ponymail-src/tools/elastic.py", line 96, in search
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'No search type for [scan]')
```

**Comment by sebbASF** [comment]
This is because ES 5 no longer supports scan.

ES scan is also used in other tools: copy-list.py, missing.py and nullfav.py

**Comment by ilgrosso** [comment]
It seems `scan`, `count` and others were [removed since ES 2.1](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_21_search_changes.html).

**Comment by sebbASF** [comment]
Deprecated, not removed.

**Comment by ilgrosso** [comment]
About the docs, you're right.
But the exception above says: `'illegal_argument_exception', 'No search type for [scan]'`, which does not look like deprecation to me.

**Comment by sebbASF** [comment]
Yes, they will have been documented as having been removed in a later (major) version.
I think you will find that scan works fine in all ES 2.x versions.

**Comment by Humbedooh** [comment]
works with anything <= 2 in major versions yes. What we need to do here is detect the major engine version, and if <= 2, then pass the scan_type, otherwise not, and then wrap the processing into a function that can work with either outputs (earlier versions will not return results on first scan, later versions will).

**Comment by sebbASF** [comment]
This was fixed in the LUA code: see #344, but has yet to be fixed in all the python tools

**Comment by Humbedooh** [comment]
The first bit can be addressed with this snippet, which I intend to commit shortly...
There will be some other future changes, as I am aware we need to switch away from doc_types altogether for newer ESes
~~~ diff
diff --git a/tools/elastic.py b/tools/elastic.py
index 897cb64..4f7517c 100755
--- a/tools/elastic.py
+++ b/tools/elastic.py
@@ -109,14 +109,24 @@ class Elastic:
         )
 
     def scan(self, doc_type='mbox', scroll='3m', size = 100, **kwargs):
-        return self.es.search(
-            index=self.dbname,
-            doc_type=doc_type,
-            search_type = 'scan',
-            size = size,
-            scroll = scroll,
-            **kwargs
-        )
+        """ Call the scan API, passing on the search type if needed (ES<=2.x) """
+        if self.engineMajor() <= 2:
+            return self.es.search(
+                index=self.dbname,
+                doc_type=doc_type,
+                search_type = 'scan',
+                size = size,
+                scroll = scroll,
+                **kwargs
+            )
+        else:
+            return self.es.search(
+                index=self.dbname,
+                doc_type=doc_type,
+                size = size,
+                scroll = scroll,
+                **kwargs
+            )
 
     def get(self, **kwargs):
         return self.es.get(index=self.dbname, **kwargs)
~~~

**Comment by Humbedooh** [comment]
for the second bit (which is rewriting edit-lists to support the two different ways of returning scrolling results), I am reworking edit-lists entirely, splitting it into a main, options and process_hits function, to avoid code duplication.

**Comment by sebbASF** [comment]
Why not take the same approach as the Lua code?
That does not need to check the ES version, but the API is a bit different so it uses a new name.
Makes it easier to migrate if the existing API is not changed.
Also easier to maintain if Lua and Python take the same approach.

**Comment by Humbedooh** [comment]
Hmm yeah, what if I just turn scan() into an iterator instead? then I can do:

for results in es.scan(blabla):
    process_results(results)

and it would process for each scroll batch...and also work with older ES versions

**Comment by Humbedooh** [comment]
so, in elastic.py I'd propose the following:

~~~ diff
diff --git a/tools/elastic.py b/tools/elastic.py
index 897cb64..8152922 100755
--- a/tools/elastic.py
+++ b/tools/elastic.py
@@ -109,14 +109,27 @@ class Elastic:
         )
 
     def scan(self, doc_type='mbox', scroll='3m', size = 100, **kwargs):
-        return self.es.search(
+        """ Run a backwards compatible scan/scroll, passing an iterator
+            that returns one page of hits per iteration. This
+            incorporates es.scoll for continuous iteration, and thus the
+            scroll() does NOT need to be called at all by the calling
+            process. """
+        results = self.es.search(
             index=self.dbname,
             doc_type=doc_type,
-            search_type = 'scan',
             size = size,
             scroll = scroll,
             **kwargs
         )
+        sid = results['_scroll_id']
+        scroll_size = results['hits']['total']
+        if results['hits'].get('hits', []):
+            yield results
+        while (scroll_size > 0):
+            results = self.scroll(scroll_id = sid, scroll = scroll)
+            sid = results['_scroll_id']
+            scroll_size = len(results['hits']['hits'])
+            yield results
 
     def get(self, **kwargs):
         return self.es.get(index=self.dbname, **kwargs)
~~~

And then in edit-lists.py, we change it to:

~~~ python
query = ...
for page in es.scan(body = query):
            proposed_changes = process_hits(page, args, dbname) # Split into separate function
~~~

**Comment by sebbASF** [comment]
Good idea to create an iterator.

As with any API change, I think it would be better to change the method name. This makes it easier to update the callers (and more obvious when all callers has been found/fixed), and means it is possible to directly test the new behaviour against the old.

It's also kinder to 3rd parties who may have written their own scripts using elastic.py.
We should deprecate the existing method in favour of the new one.

**Comment by Humbedooh** [comment]
I've added the scan_and_scroll type (while keeping the original scan as it was), and revamped edit-lists.py by spliting the process into distinct functions. @ilgrosso can you please test that this works on your system? It works on mine, but I was only testing with a handful of emails.

**Comment by ilgrosso** [comment]
@Humbedooh with last changes, this command:

```python3 edit-list.py --delete --source "idal2.tirasa.net"```

works fine, thanks!

**Comment by Humbedooh** [comment]
Great, I'm going to close this as fixed then.
Later on, we'll look into enabling support for 6.x/7.x, which requires a bit of rewriting and detecting when it's a >= 6.x system (since doc_type went away)
