### ISSUE TITLE
Bug: should not generate invalid list ids

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#511]
Currently a list-Id header of the form:

List-Id: "SpamAssassin Users" users@spamassassin.apache.org

is not parsed correctly, whereas the following are:

List-Id: "SpamAssassin Users" <users@spamassassin.apache.org>
List-Id: <users@spamassassin.apache.org>
List-Id: users@spamassassin.apache.org

The descriptive phrase should be completely ignored when extracting the list-id

**Comment by Humbedooh** [comment]
None of those would be valid according to https://tools.ietf.org/html/rfc2919
However, we might as well be lenient in what we accept.
