### ISSUE TITLE
mbox export via API not behaving as expected

### ISSUE THREAD

**Issue by rhenwood-arm** [apache/incubator-ponymail#514]
Hi, 

I'm trying to get an MBOX via the API and the file returned is zero bytes. Here is an example of the request I'm trying:

https://lists.apache.org/api/mbox.lua?list=dev&domain=accumulo.apache.org&date=2020-01

**Comment by Humbedooh** [comment]
For that specific list, you would need https://lists.apache.org/api/mbox.lua?list=dev@accumulo.apache.org&date=2020-01
That is, the domain and list part is one combined argument.

**Comment by rhenwood-arm** [comment]
ah! Thanks!
