### ISSUE TITLE
Invalid mailing list address supplied

### ISSUE THREAD

**Issue by gmcdonald** [apache/incubator-ponymail#516]
When viewing a mailing list - which does exist - but has an underscore in the list name, the error message pops up with 'Invalid mailing list address supplied!' , you can close the error message and then continue on to read the message or view the list.

I'm not sure if the underscore is the problem, but I found it happen on two lists with underscores, and nowhere else (so far)

**Comment by gmcdonald** [comment]
For an actual reproducible example see this ticket:

https://issues.apache.org/jira/browse/INFRA-20367

**Comment by Humbedooh** [comment]
This should be fixed now, sorry for the late reply.

**Comment by sebbASF** [comment]
The generated ponymail.js script was not updated
