### ISSUE TITLE
Is it possible to put someone on copy when replying to mailing list in browser?

### ISSUE THREAD

**Issue by plainheart** [apache/incubator-ponymail#525]
Hi, 

I'd like to know if I can put someone on copy when I reply to someone in a thread through the browser?

Usually, I will take my apache email account to reply to the mailing list, but I find it seems that I can't copy anyone.

It would be better to support this function. Thanks!

**Comment by raboof** [comment]
Was this completed or abandoned? I would like this as well and I don't see it available on https://lists.apache.org yet AFAICS

**Comment by Humbedooh** [comment]
The ticket was closed after a few days, so I guess it wasn't looked into.
As for that specific instance (lists.a.o), it would not be possible to cc a non-mailing-list due to policy restrictions.

**Comment by raboof** [comment]
In this case I wanted to loop in another mailinglist, so it might still have been useful :). Should we re-open this one or open a new issue?

**Comment by plainheart** [comment]
I'm glad to hear from you, although it has past for a long time. I bound my apache email with gmail to send email, which allows me to cc someone. But it would be great if we can directly do this via mailling list.
