### ISSUE TITLE
Bug: message added to wrong mbox file

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#53]
The email with message Id
<CAOGo0VYmoPyFiV1irTkKnVe37Pmoja-Zs80D33vQ3YuaRsBNgA@mail.gmail.com>

appears in the downloaded mailbox for March, i.e.

https://lists.apache.org/api/mbox.lua?list=dev@whimsical.apache.org&date=2016-3

Since the mail was sent in February, that is the wrong mbox.

**Comment by Humbedooh** [comment]
I suppose that would technically be an ElasticSearch issue.
the mbox script downloads everything from 2016-03-01 to 2016-03-31 there, so if that email makes it to the blob, then it's probably a locale issue within ElasticSearch.

**Comment by sebbASF** [comment]
I'm not sure I follow: there should not be an issue with the Locale, because the mail message includes the timezone:

Date: Mon, 29 Feb 2016 23:11:02 +0000

Maybe the problem is that the query does not include the timezone.

**Comment by Humbedooh** [comment]
Cannot reproduce. I think this is/was an old bug that has been fixed since (maybe in Sam's rewrite?). The email is probably off by one hour because of some daylight savings time during the import, and thus counts as being in March.
