### ISSUE TITLE
Bug: Internal Server Error when viewing e-mails

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#60]
Got the following Internal Server Error when viewing mail:

/var/www/ponymail_asf/site/api/email.lua:32: attempt to get length of field 'cc' (a userdata value)

The mailbox that causes the problem is:

https://lists.apache.org/list.html?notifications@whimsical.apache.org:2016-4

**Comment by ulises** [comment]
I seem to be able to see that just fine?
