### ISSUE TITLE
Bug: date display shows the negative timezone offset

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#63]
The date display has been changed to append the tz offset.
However the sign is inverted.

For example:
https://lists.apache.org/thread.html/Zfp0souj6y08k06
has the source:
Date: Wed, 1 Jun 2016 11:23:56 -0500
This is correctly shown by mail-archives as
Date Wed, 01 Jun 2016 16:23:56 GMT
However Pony Mail shows it to me as
Date: 2016-06-01 17:23 (-0100)

However I'm on GMT+1.

Seems to me that the display should use GMT and avoid any issues with time conversion, especially since DST dates vary between locales.

But if conversion to local time is done, it's important to show the correct offset.

**Comment by Humbedooh** [comment]
This was fixed in 19da4b5dd
