### ISSUE TITLE
Bug: Pony Mail does not handle blocked access to local storage well

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#65]
Using Version:	37.0.2178.54
Update stream:	Stable
System:	Mac OS X 10.11.5 64-bit

The home page display is OK, but the mail list pages are empty apart from the header.
The next line shows the selected list and an empty "View Mode" drop-down.

**Comment by Humbedooh** [comment]
We'll need some javascript console output to go on, this is insufficient data.

**Comment by sebbASF** [comment]
Fails to access: window.localStorage

I'd forgotten that I had configured the browser this way.
I agree it's unusual, but the code ought to allow for this restriction.

**Comment by Humbedooh** [comment]
a line number would be nice :)

**Comment by sebbASF** [comment]
2282

**Comment by Humbedooh** [comment]
ugh, that's a nasty behavior by Opera. That line tries to assert whether window.localStorage exists, and should just return false in this case. That it turns into an error seems counterproductive.

We can work around this apparent bug in Opera, but that's gonna take a lot of work, as we use storage in many places.

**Comment by sebbASF** [comment]
Chrome behaves the same way if you select "Block sites from setting any data"

**Comment by sebbASF** [comment]
Safari behaves the same as well, and has some other complaints:
[Error] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
	loadStateData (content1.js (line 2:180))
	global code (content1.js (line 2:4859))

[Error] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
	loadEphemeral (ponymail.js:2282)
	buildPage (ponymail.js:3823)
	onreadystatechange (ponymail.js:2228)

**Comment by Humbedooh** [comment]
yes, they are all webkit these days. 
I've made a workaround, though it bugs me that these browsers behave so poorly. They should just set the storage objects to null if they're not accessible.

**Comment by sebbASF** [comment]
If there is a standard for how the browsers should behave, then raise an error against webkit

**Comment by Humbedooh** [comment]
already exists: http://crbug.com/357625
