### ISSUE TITLE
Bug: incorrect date calculation

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#66]
The message https://lists.apache.org/thread.html/Ztfzmhd8tf3q0li shows the following date:

Date: 2016-03-18 07:26 (+0100)

However View Source shows:

Date: Fri, 18 Mar 2016 07:26:28 +0000

That should be shown as:
Date: 2016-03-18 08:26 (+0100)

I tried to find other e-mails with the same issue but so far have failed.
It's not just the +0000 in the source; it may relate to other items in the source.

**Comment by Humbedooh** [comment]
this is not incorrect per se, it's just a conversion from the original date to your own timezone. The TZ of an email is not saved in the digest.

**Comment by Humbedooh** [comment]
that is to say, all timestamps are converted to UTC before they are saved.
If you wish to know the author's timezone, you need to view the source. This is not something that will be changed in the near future.

**Comment by sebbASF** [comment]
The problem here is that the author's timezone is +0000 according to View Source.

Mine is +0100.

Yet they display the **same** time, i.e. 07:26

That's not possible; there is no time t such that

t + 0000 == t + 0100
