### ISSUE TITLE
Build and publish website per commit

### ISSUE THREAD

**Issue by gmcdonald** [apache/incubator-ponymail#67]
Rather than generating the site yourself, just edit a source file and forget about it!

Assuming the build is successful, buildbot will publish the website for us.

There has been a discussion started on the dev list about this, this issue is to track its progress.

**Comment by Humbedooh** [comment]
Discussion at: https://lists.apache.org/thread.html/7d8607ae4ba832e5d1dd3f7ef0ca14e2dde9bf377d4bed1a8aee7dab@%3Cdev.ponymail.apache.org%3E

**Comment by gmcdonald** [comment]
After a little snag with the auth system, this is now working.

Just commit to the 'source' dir and that'll trigger a rebuild and publish.

Buildbot config for this is at -

https://svn.apache.org/repos/infra/infrastructure/buildbot/aegis/buildmaster/master1/projects/ponymail.conf 
First successful buildbot build result at -

https://ci.apache.org/builders/ponymail-site/builds/9

Note that only commit to the 'source' dir should trigger a build + publish
