### ISSUE TITLE
Bug: Pony Mail silently drops mail messages if there are too many

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#72]
The spark reviews list has over 17,000 messages in May 2016.

http://mail-archives.apache.org/mod_mbox/spark-reviews/201605.mbox/browser

However Pony Mail only shows 8 topics (24 mails):

https://lists.apache.org/list.html?reviews@spark.apache.org:2016-05

There is no indication that there are additional messages in that month, and there does not appear to be any way to list all the messages for the month.

No messages at all are shown for June.

**Comment by Humbedooh** [comment]
Can you provide any evidence that this is an issue with Pony Mail?

**Comment by sebbASF** [comment]
Not sure what you mean by proof.

Or are you saying that Pony Mail has not been supplied with any mails for that list since May 1st?

**Comment by Humbedooh** [comment]
This is an issue tracker for Pony Mail the project, not the specific deployment on lists.apache.org.
If something is wrong with that specific instance, I'd think the first thing you want to do is make sure it's an issue with Pony Mail and not that someone forgot to sub a list to the archiver on lists.apache.org
