### ISSUE TITLE
Grammar fix

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#73]
"No emails found fitting this criteria"
should be
"No emails found fitting these criteria"

**Comment by gmcdonald** [comment]
'these criteria' implies more than one set of search patterns, 'this criteria' means exactly one, who is to say which is more correct.

**Comment by sebbASF** [comment]
The word criteria is plural. 
Its singular is criterion.

So either say

"This criterion" or "These criteria"

As far as the end user is concerned, each search involves several conditions (criteria).
These are: the list name and the date range and perhaps the subject

This is why it should be "These criteria"

**Comment by sebbASF** [comment]
Or it could be

"No emails found that fit the search criteria"
