### ISSUE TITLE
Bug: MID (medium) is not stable as it depends on the local timezone

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#85]
The mid hash which is calculated in "medium" generator mode is based on input which includes the value of the variable: mdatestring [1]

Now this variable is derived as follows [2]

mdatestring = time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(email.utils.mktime_tz(mdate)))

where mdate is the Date: header (as a default).

This means that the mdatestring value depends on the local timezone of the server where the archiver script is run, i.e. the generated message-id will change if the local timezone is changed.

So if the same mail is re-imported after changing the timezone, it will get a different id.
Or if the mail archive is reloaded on a different host with a different TZ setting.

That seems wrong; the id should only depend on the input mail message.

[1] https://github.com/apache/incubator-ponymail/blob/master/tools/archiver.py#L305
[2] https://github.com/apache/incubator-ponymail/blob/master/tools/archiver.py#L274

**Comment by sebbASF** [comment]
Note: AIUI the mid is used for creating PermaLinks; these need to be stable.

**Comment by Humbedooh** [comment]
Shouldn't this simply be a PR? :)

**Comment by sebbASF** [comment]
There are two aspects to the bug:
1) fixing the code so it is not dependent on the locale for future MID calculations.
2) ensuring that existing installations are not affected by the change to a fixed time-zone.

I think the latter means that each installation needs to have a configuration item that records the timezone that was (and is) used for all such calculations. For new installations this should default to UTC. For existing installations it obviously needs to be set to the appropriate timezone.

**Comment by sebbASF** [comment]
It looks as though the code has already been fixed in (f6f453e) to use:

mdatestring = time.strftime("%Y/%m/%d %H:%M:%S", time.gmtime(email.utils.mktime_tz(mdate)))

If there are any installations that used the "medium" generator with a time zone other than UTC then I expect the MIDs and Permalinks will break when the installation is updated.
