### ISSUE TITLE
aaa.lua assumes that list domain == LDAP committee group name

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#92]
The ASF aaa.lua module assumes that members of the LDAP committee group 'xyz' have access to the private mails for mailing lists with the domain 'xyz'.

This is true for most TLPs, but there are some exceptions, including:

httpcomponents/hc
whimsy/whimsical

Note that the file https://whimsy.apache.org/public/committee-info.json provides a mail_list entry for each committee name.

**Comment by Humbedooh** [comment]
Not a Pony Mail issue, that's internal to ASF
