### ISSUE TITLE
Inefficient ldapsearch in ASF aaa.lua#getPMCs

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#93]
The getPMCs function uses the following search:

ldapsearch -x -LLL "(|(memberUid=%s)(member=uid=%s,ou=people,dc=apache,dc=org))" cn

However, memberUid is not used for LDAP committee groups.
Also the cn attribute is not needed.

The query could be simplified to:

ldapsearch -x -LLL "member=uid=%s,ou=people,dc=apache,dc=org" dn

Alternatively, the code could just use the Whimsy JSON file

https://whimsy.apache.org/public/public_ldap_committees.json

**Comment by Humbedooh** [comment]
Sebastian, the AAA module bundled with Pony Mail is an example. To my knowledge, it is not in use anywhere, nor should it be.
